global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text.Json.Serialization;
global using Microsoft.EntityFrameworkCore;
global using MinimalApiTutorial.Api;
global using MinimalApiTutorial.Config;
global using MinimalApiTutorial.Data;
global using MinimalApiTutorial.Models;
global using MinimalApiTutorial.Services;
